sql-- CREATE STAGING TABLES
CREATE OR REPLACE TABLE STG_LINEITEM LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
CREATE OR REPLACE TABLE STG_ORDERS LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
CREATE OR REPLACE TABLE STG_PARTSUPP LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;
CREATE OR REPLACE TABLE STG_PART LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
CREATE OR REPLACE TABLE STG_SUPPLIER LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;
CREATE OR REPLACE TABLE STG_CUSTOMER LIKE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- CREATE DIMENSION TABLE
CREATE OR REPLACE TABLE DIM_CUSTOMERS (
    customer_key INT,
    customer_name VARCHAR,
    market_segment VARCHAR,
    acct_balance NUMBER(15,2),
    phone_number VARCHAR,
    dw_load_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREATE FACT TABLE
CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
    order_item_id VARCHAR, -- Composite unique key
    order_key INT,
    customer_key INT,
    part_key INT,
    supplier_key INT,
    line_number INT,
    order_date DATE,
    quantity NUMBER(12,2),
    extended_price NUMBER(12,2),
    discount NUMBER(12,2),
    tax NUMBER(12,2),
    net_revenue NUMBER(12,2),
    supply_cost NUMBER(12,2),
    dw_load_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);